SELECT 
    COADD_OBJECT_ID, 
    RA, DEC, KRON_RADIUS, A_IMAGE, B_IMAGE, ERRA_IMAGE, 
    ERRB_IMAGE, ERRTHETA_IMAGE, XWIN_IMAGE, YWIN_IMAGE, EBV_SFD98, EBV_LENZ17, 
    EBV_PLANCK13, MAG_DETMODEL_G, MAG_AUTO_G, MAG_APER_8_G, WAVG_MAG_PSF_G, MAGERR_DETMODEL_G, 
    MAGERR_AUTO_G, MAGERR_APER_8_G, WAVG_MAGERR_PSF_G, FLUX_DETMODEL_G, FLUX_AUTO_G, WAVG_FLUX_PSF_G, 
    FLUX_RADIUS_G, FLUX_APER_8_G, FLUXERR_DETMODEL_G, FLUXERR_AUTO_G, WAVG_FLUXERR_PSF_G, FLUXERR_APER_8_G, 
    MU_EFF_MODEL_G, MU_MAX_G, MU_MAX_MODEL_G, MU_MEAN_MODEL_G, MU_THRESHOLD_G, SPREADERR_MODEL_G, 
    SPREAD_MODEL_G, CLASS_STAR_G, NITER_MODEL_G, WAVG_SPREADERR_MODEL_G, WAVG_SPREAD_MODEL_G, SEXTRACTOR_FLAGS_G, 
    IMAFLAGS_ISO_G, NEPOCHS_G, MAG_DETMODEL_R, MAG_AUTO_R, MAG_APER_8_R, WAVG_MAG_PSF_R, 
    MAGERR_DETMODEL_R, MAGERR_AUTO_R, MAGERR_APER_8_R, WAVG_MAGERR_PSF_R, FLUX_DETMODEL_R, FLUX_AUTO_R, 
    WAVG_FLUX_PSF_R, FLUX_RADIUS_R, FLUX_APER_8_R, FLUXERR_DETMODEL_R, FLUXERR_AUTO_R, WAVG_FLUXERR_PSF_R, 
    FLUXERR_APER_8_R, MU_EFF_MODEL_R, MU_MAX_R, MU_MAX_MODEL_R, MU_MEAN_MODEL_R, MU_THRESHOLD_R, 
    SPREADERR_MODEL_R, SPREAD_MODEL_R, CLASS_STAR_R, NITER_MODEL_R, WAVG_SPREADERR_MODEL_R, WAVG_SPREAD_MODEL_R, 
    SEXTRACTOR_FLAGS_R, IMAFLAGS_ISO_R, NEPOCHS_R, MAG_DETMODEL_I, MAG_AUTO_I, MAG_APER_8_I, 
    WAVG_MAG_PSF_I, MAGERR_DETMODEL_I, MAGERR_AUTO_I, MAGERR_APER_8_I, WAVG_MAGERR_PSF_I, FLUX_DETMODEL_I, 
    FLUX_AUTO_I, WAVG_FLUX_PSF_I, FLUX_RADIUS_I, FLUX_APER_8_I, FLUXERR_DETMODEL_I, FLUXERR_AUTO_I, 
    WAVG_FLUXERR_PSF_I, FLUXERR_APER_8_I, MU_EFF_MODEL_I, MU_MAX_I, MU_MAX_MODEL_I, MU_MEAN_MODEL_I, 
    MU_THRESHOLD_I, SPREADERR_MODEL_I, SPREAD_MODEL_I, CLASS_STAR_I, NITER_MODEL_I, WAVG_SPREADERR_MODEL_I, 
    WAVG_SPREAD_MODEL_I, SEXTRACTOR_FLAGS_I, IMAFLAGS_ISO_I, NEPOCHS_I, MAG_DETMODEL_Z, MAG_AUTO_Z, 
    MAG_APER_8_Z, WAVG_MAG_PSF_Z, MAGERR_DETMODEL_Z, MAGERR_AUTO_Z, MAGERR_APER_8_Z, WAVG_MAGERR_PSF_Z, 
    FLUX_DETMODEL_Z, FLUX_AUTO_Z, WAVG_FLUX_PSF_Z, FLUX_RADIUS_Z, FLUX_APER_8_Z, FLUXERR_DETMODEL_Z, 
    FLUXERR_AUTO_Z, WAVG_FLUXERR_PSF_Z, FLUXERR_APER_8_Z, MU_EFF_MODEL_Z, MU_MAX_Z, MU_MAX_MODEL_Z, 
    MU_MEAN_MODEL_Z, MU_THRESHOLD_Z, SPREADERR_MODEL_Z, SPREAD_MODEL_Z, CLASS_STAR_Z, NITER_MODEL_Z, 
    WAVG_SPREADERR_MODEL_Z, WAVG_SPREAD_MODEL_Z, SEXTRACTOR_FLAGS_Z, IMAFLAGS_ISO_Z, NEPOCHS_Z, MAG_DETMODEL_Y, 
    MAG_AUTO_Y, MAG_APER_8_Y, WAVG_MAG_PSF_Y, MAGERR_DETMODEL_Y, MAGERR_AUTO_Y, MAGERR_APER_8_Y, 
    WAVG_MAGERR_PSF_Y, FLUX_DETMODEL_Y, FLUX_AUTO_Y, WAVG_FLUX_PSF_Y, FLUX_RADIUS_Y, FLUX_APER_8_Y, 
    FLUXERR_DETMODEL_Y, FLUXERR_AUTO_Y, WAVG_FLUXERR_PSF_Y, FLUXERR_APER_8_Y, MU_EFF_MODEL_Y, MU_MAX_Y, 
    MU_MAX_MODEL_Y, MU_MEAN_MODEL_Y, MU_THRESHOLD_Y, SPREADERR_MODEL_Y, SPREAD_MODEL_Y, CLASS_STAR_Y, 
    NITER_MODEL_Y, WAVG_SPREADERR_MODEL_Y, WAVG_SPREAD_MODEL_Y, SEXTRACTOR_FLAGS_Y, IMAFLAGS_ISO_Y, NEPOCHS_Y, 
    MOF_PSF_MAG_ERR_G, MOF_CM_MAG_ERR_G, MOF_PSF_MAG_ERR_R, MOF_CM_MAG_ERR_R, MOF_PSF_MAG_ERR_I, MOF_CM_MAG_ERR_I, 
    MOF_PSF_MAG_ERR_Z, MOF_CM_MAG_ERR_Z, MOF_CM_T, MOF_CM_T_ERR, MOF_CM_FLUX_COV_G_G, MOF_CM_FLUX_COV_R_R, 
    MOF_CM_FLUX_COV_I_I, MOF_CM_FLUX_COV_Z_Z, MOF_CM_FLUX_G, MOF_CM_FLUX_R, MOF_CM_FLUX_I, MOF_CM_FLUX_Z, 
    MOF_CM_FLUX_S2N_G, MOF_CM_FLUX_S2N_R, MOF_CM_FLUX_S2N_I, MOF_CM_FLUX_S2N_Z, MOF_CM_MAG_G, MOF_CM_MAG_R, 
    MOF_CM_MAG_I, MOF_CM_MAG_Z, MOF_CM_LOGSB_G, MOF_CM_LOGSB_R, MOF_CM_LOGSB_I, MOF_CM_LOGSB_Z, 
    MOF_CM_G_1, MOF_CM_G_2, MOF_CM_G_COV_1_1, MOF_CM_G_COV_1_2, MOF_CM_G_COV_2_1, MOF_CM_G_COV_2_2, 
    MOF_CM_CHI2PER, MOF_CM_DOF, MOF_CM_FRACDEV, MOF_CM_FRACDEV_NOCLIP, MOF_CM_FRACDEV_ERR, MOF_CM_TDBYTE, 
    MOF_FLAGS, MOF_PSF_FLUX_G, MOF_PSF_FLUX_R, MOF_PSF_FLUX_I, MOF_PSF_FLUX_Z, MOF_PSF_FLUX_ERR_G, 
    MOF_PSF_FLUX_ERR_R, MOF_PSF_FLUX_ERR_I, MOF_PSF_FLUX_ERR_Z, MOF_PSF_MAG_G, MOF_PSF_MAG_R, MOF_PSF_MAG_I, 
    MOF_PSF_MAG_Z, MOF_PSF_FLUX_S2N_G, MOF_PSF_FLUX_S2N_R, MOF_PSF_FLUX_S2N_I, MOF_PSF_FLUX_S2N_Z, MOF_CM_MAG_CORRECTED_G, 
    MOF_CM_MAG_CORRECTED_R, MOF_CM_MAG_CORRECTED_I, MOF_CM_MAG_CORRECTED_Z, SOF_CM_CHI2PER, SOF_CM_DOF, SOF_CM_FRACDEV, 
    SOF_CM_FRACDEV_NOCLIP, SOF_CM_FRACDEV_ERR, SOF_CM_TDBYTE, SOF_PSF_MAG_ERR_G, SOF_CM_MAG_ERR_G, SOF_PSF_MAG_ERR_R, 
    SOF_CM_MAG_ERR_R, SOF_PSF_MAG_ERR_I, SOF_CM_MAG_ERR_I, SOF_PSF_MAG_ERR_Z, SOF_CM_MAG_ERR_Z, SOF_CM_T, 
    SOF_CM_T_ERR, SOF_CM_FLUX_COV_G_G, SOF_CM_FLUX_COV_R_R, SOF_CM_FLUX_COV_I_I, SOF_CM_FLUX_COV_Z_Z, SOF_CM_FLUX_G, 
    SOF_CM_FLUX_R, SOF_CM_FLUX_I, SOF_CM_FLUX_Z, SOF_CM_FLUX_S2N_G, SOF_CM_FLUX_S2N_R, SOF_CM_FLUX_S2N_I, 
    SOF_CM_FLUX_S2N_Z, SOF_CM_MAG_G, SOF_CM_MAG_R, SOF_CM_MAG_I, SOF_CM_MAG_Z, SOF_CM_LOGSB_G, 
    SOF_CM_LOGSB_R, SOF_CM_LOGSB_I, SOF_CM_LOGSB_Z, SOF_CM_G_1, SOF_CM_G_2, SOF_CM_G_COV_1_1, 
    SOF_CM_G_COV_1_2, SOF_CM_G_COV_2_1, SOF_CM_G_COV_2_2, SOF_FLAGS, SOF_PSF_FLUX_G, SOF_PSF_FLUX_R, 
    SOF_PSF_FLUX_I, SOF_PSF_FLUX_Z, SOF_PSF_FLUX_ERR_G, SOF_PSF_FLUX_ERR_R, SOF_PSF_FLUX_ERR_I, SOF_PSF_FLUX_ERR_Z, 
    SOF_PSF_MAG_G, SOF_PSF_MAG_R, SOF_PSF_MAG_I, SOF_PSF_MAG_Z, SOF_PSF_FLUX_S2N_G, SOF_PSF_FLUX_S2N_R, 
    SOF_PSF_FLUX_S2N_I, SOF_PSF_FLUX_S2N_Z, SOF_CM_MAG_CORRECTED_G, SOF_CM_MAG_CORRECTED_R, SOF_CM_MAG_CORRECTED_I, SOF_CM_MAG_CORRECTED_Z, 
    FRAC_DET_GRIZ, FRAC_DET_GRIZY, N_IMAGES_G, N_IMAGES_R, N_IMAGES_I, N_IMAGES_Z, 
    N_IMAGES_Y, FLAGS_FOOTPRINT, FLAGS_FOREGROUND, FLAGS_GOLD, FLAGS_BADREGIONS, EXTENDED_CLASS_COADD, 
    EXTENDED_CLASS_MASH_SOF, EXTENDED_CLASS_MASH_MOF, EXTENDED_CLASS_MOF, EXTENDED_CLASS_SOF, EXTENDED_CLASS_WAVG, DELTA_MAG_CHROM_G, 
    DELTA_MAG_CHROM_R, DELTA_MAG_CHROM_I, DELTA_MAG_CHROM_Z, DELTA_MAG_CHROM_Y, DELTA_MAG_Y4_G, DELTA_MAG_Y4_R, 
    DELTA_MAG_Y4_I, DELTA_MAG_Y4_Z, DELTA_MAG_Y4_Y, A_FIDUCIAL_G, A_FIDUCIAL_I, A_FIDUCIAL_R, 
    A_FIDUCIAL_Y, A_FIDUCIAL_Z, A_SED_LENZ17_G, A_SED_LENZ17_I, A_SED_LENZ17_R, A_SED_LENZ17_Y, 
    A_SED_LENZ17_Z, A_SED_PLANCK13_G, A_SED_PLANCK13_I, A_SED_PLANCK13_R, A_SED_PLANCK13_Y, A_SED_PLANCK13_Z, 
    A_SED_SFD98_G, A_SED_SFD98_I, A_SED_SFD98_R, A_SED_SFD98_Y, A_SED_SFD98_Z, BPZ_ZMEAN_SOF, 
    BPZ_ZMC_SOF, BPZ_ZSIGMA_SOF, BPZ_ZSIGMA68_SOF, BPZ_ZMODE_SOF, BPZ_TEMPLATE_ID_SOF, BPZ_ZMEAN_MOF, 
    BPZ_ZMC_MOF, BPZ_ZSIGMA_MOF, BPZ_ZSIGMA68_MOF, BPZ_ZMODE_MOF, BPZ_TEMPLATE_ID_MOF, DNF_ZMC_MOF, 
    DNF_ZMEAN_MOF, DNF_ZSIGMA_MOF, DNF_ZMC_SOF, DNF_ZMEAN_SOF, DNF_ZSIGMA_SOF, MAG_PSF_G, 
    MAG_PSF_R, MAG_PSF_I, MAG_PSF_Z, MAG_PSF_Y, MAGERR_PSF_G, MAGERR_PSF_R, 
    MAGERR_PSF_I, MAGERR_PSF_Z, MAGERR_PSF_Y
FROM
    Y3_GOLD
WHERE
    -- remove point sources
    EXTENDED_CLASS_COADD != 0 and
    SPREAD_MODEL_I + 5/3*SPREADERR_MODEL_I > 0.007 and
    -- surface brightness and radius cuts
    (FLUX_RADIUS_G between 2.5 and 20) and
    (MU_MEAN_MODEL_G between 24.2 and 28.8) and
    -- ellipticity cut
    ((1 - B_IMAGE/A_IMAGE) < 0.7) and
    -- color cuts
    (MAG_AUTO_G-MAG_AUTO_I between -0.1 and 1.4) and
    (MAG_AUTO_G - MAG_AUTO_R) > 0.7*(MAG_AUTO_G - MAG_AUTO_I) - 0.4 and
    (MAG_AUTO_G - MAG_AUTO_R) < 0.7*(MAG_AUTO_G - MAG_AUTO_I) + 0.4 and
    -- remove NULL items
    MOF_FLAGS is not NULL and
    SOF_FLAGS is not NULL and
    EXTENDED_CLASS_COADD != -9 and
    EXTENDED_CLASS_MASH_SOF != -9 and
    EXTENDED_CLASS_MASH_MOF != -9 and
    EXTENDED_CLASS_MOF != -9 and
    EXTENDED_CLASS_SOF != -9 and
    EXTENDED_CLASS_WAVG != -9